### ISSUE TITLE
check and throw error if -bs and -rf are both specified

### ISSUE THREAD

**Issue by vivekbhr** [maxplanck-ie/HiCExplorer#133] opened 2017-10-05 08:55 UTC
HicBuild matrix throws an error if the matrix is created with both `--binSize` as well as `----restrictionSequence ` argument. But it doesn't stop (atleast on snakemake). We should explicitly check for this and either override one argument with another (-bs with -rf), with a warning or simply throw an error in the beginning of the job itself..

**Comment by joachimwolff** [comment] 2017-10-05 10:03
Indeed, I remember that there was some issue with these two arguments, let me validate it.

Can you check the behaviour if a restrictionCutFile and a restrictionSequence is given?

**Comment by joachimwolff** [comment] 2017-10-05 11:23
@vivekbhr Can you post the error message? I cannot reproduce it.

**Comment by joachimwolff** [comment] 2017-11-07 11:02
We could not reproduce it and I think these two arguments do not influence or interact with each other. Therefore I am closing this issue.

**Closed by joachimwolff** 2017-11-07 11:02 UTC
